# Generated by Django 6.0.4 on 2026-04-18 23:05

import cards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aadhaar', models.CharField(max_length=14)),
                ('pan_passport', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=4)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('disability_status', models.CharField(blank=True, default='None', max_length=50)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('past_surgeries', models.TextField(blank=True)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_relation', models.CharField(max_length=50)),
                ('emergency_mobile', models.CharField(max_length=15)),
                ('emergency_mobile2', models.CharField(blank=True, max_length=15)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('sum_insured', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_expiry', models.DateField(blank=True, null=True)),
                ('tpa', models.CharField(blank=True, max_length=100)),
                ('scheme_pmjay', models.BooleanField(default=False)),
                ('scheme_state', models.BooleanField(default=False)),
                ('scheme_bpl', models.BooleanField(default=False)),
                ('scheme_defence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(default=cards.models.generate_card_id, max_length=20, unique=True)),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(default=cards.models.card_expiry)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CardRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('new_expiry', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='cards.smartcard')),
            ],
        ),
        migrations.CreateModel(
            name='CardDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('delivery_mobile', models.CharField(max_length=15)),
                ('preferred_slot', models.CharField(choices=[('morning', 'Morning (9 AM – 1 PM)'), ('afternoon', 'Afternoon (1 PM – 5 PM)'), ('evening', 'Evening (5 PM – 8 PM)'), ('any', 'Any Time')], default='any', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='processing', max_length=30)),
                ('tracking_id', models.CharField(blank=True, max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='cards.smartcard')),
            ],
        ),
    ]
